import App from 'next/app'
import { 
  
    Md3DRotation
    ,MdAccessibility
    ,MdAccessible
    ,MdAccountBalance
    ,MdAccountBalanceWallet
    ,MdAccountBox
    ,MdAccountCircle
    ,MdAddShoppingCart
    ,MdAlarm
    ,MdAlarmAdd
    ,MdAlarmOff
    ,MdAlarmOn
    ,MdAllOut
    ,MdAndroid
    ,MdAnnouncement
    ,MdAspectRatio
    ,MdAssessment
    ,MdAssignment
    ,MdAssignmentInd
    ,MdAssignmentLate
    ,MdAssignmentReturn
    ,MdAssignmentReturned
    ,MdAssignmentTurnedIn
    ,MdAutorenew
    ,MdBackup
    ,MdBook
    ,MdBookmark
    ,MdBookmarkBorder
    ,MdBugReport
    ,MdBuild
    ,MdCached
    ,MdCameraEnhance
    ,MdCardGiftcard
    ,MdCardMembership
    ,MdCardTravel
    ,MdChangeHistory
    ,MdCheckCircle
    ,MdChromeReaderMode
    ,MdClass
    ,MdCode
    ,MdCompareArrows
    ,MdCopyright
    ,MdCreditCard
    ,MdDashboard
    ,MdDateRange
    ,MdDelete
    ,MdDeleteForever
    ,MdDescription
    ,MdDns
    ,MdDone
    ,MdDoneAll
    ,MdDonutLarge
    ,MdDonutSmall
    ,MdEject
    ,MdEuroSymbol
    ,MdEvent
    ,MdEventSeat
    ,MdExitToApp
    ,MdExplore
    ,MdExtension
    ,MdFace
    ,MdFavorite
    ,MdFavoriteBorder
    ,MdFeedback
    ,MdFindInPage
    ,MdFindReplace
    ,MdFingerprint
    ,MdFlightLand
    ,MdFlightTakeoff
    ,MdFlipToBack
    ,MdFlipToFront
    ,MdGTranslate
    ,MdGavel
    ,MdGetApp
    ,MdGif
    ,MdGrade
    ,MdGroupWork
    ,MdHelp
    ,MdHelpOutline
    ,MdHighlightOff
    ,MdHistory
    ,MdHome
    ,MdHourglassEmpty
    ,MdHourglassFull
    ,MdHttp
    ,MdHttps
    ,MdImportantDevices
    ,MdInfo
    ,MdInfoOutline
    ,MdInput
    ,MdInvertColors
    ,MdLabel
    ,MdLabelOutline
    ,MdLanguage
    ,MdLaunch
    ,MdLightbulbOutline
    ,MdLineStyle
    ,MdLineWeight
    ,MdList
    ,MdLock
    ,MdLockOpen
    ,MdLockOutline
    ,MdLoyalty
    ,MdMarkunreadMailbox
    ,MdMotorcycle
    ,MdNoteAdd
    ,MdOfflinePin
    ,MdOpacity
    ,MdOpenInBrowser
    ,MdOpenInNew
    ,MdOpenWith
    ,MdPageview
    ,MdPanTool
    ,MdPayment
    ,MdPermCameraMic
    ,MdPermContactCalendar,MdPermDataSetting
    ,MdPermDeviceInformation
    ,MdPermIdentity
    ,MdPermMedia
    ,MdPermPhoneMsg
    ,MdPermScanWifi
    ,MdPets
    ,MdPictureInPicture
    ,MdPictureInPictureAlt
    ,MdPlayForWork
    ,MdPolymer
    ,MdPowerSettingsNew
    ,MdPregnantWoman
    ,MdPrint
    ,MdQueryBuilder
    ,MdQuestionAnswer
    ,MdReceipt
    ,MdRecordVoiceOver
    ,MdRedeem
    ,MdRemoveShoppingCart
    ,MdReorder
    ,MdReportProblem
    ,MdRestore
    ,MdRestorePage
    ,MdRoom
    ,MdRoundedCorner
    ,MdRowing
    ,MdSchedule
    ,MdSearch
    ,MdSettings
    ,MdSettingsApplications
    ,MdSettingsBackupRestore
    ,MdSettingsBluetooth
    ,MdSettingsBrightness
    ,MdSettingsCell
    ,MdSettingsEthernet
    ,MdSettingsInputAntenna
    ,MdSettingsInputComponent
    ,MdSettingsInputComposite
    ,MdSettingsInputHdmi
    ,MdSettingsInputSvideo
    ,MdSettingsOverscan
    ,MdSettingsPhone
    ,MdSettingsPower
    ,MdSettingsRemote
    ,MdSettingsVoice
    ,MdShop
    ,MdShopTwo
    ,MdShoppingBasket
    ,MdShoppingCart
    ,MdSpeakerNotes
    ,MdSpeakerNotesOff
    ,MdSpellcheck
    ,MdStars
    ,MdStore
    ,MdSubject
    ,MdSupervisorAccount
    ,MdSwapHoriz
    ,MdSwapVert
    ,MdSwapVerticalCircle
    ,MdSystemUpdateAlt
    ,MdTab
    ,MdTabUnselected
    ,MdTheaters
    ,MdThumbDown
    ,MdThumbUp
    ,MdThumbsUpDown
    ,MdTimeline
    ,MdToc
    ,MdToday
    ,MdToll
    ,MdTouchApp
    ,MdTrackChanges
    ,MdTranslate
    ,MdTrendingDown
    ,MdTrendingFlat
    ,MdTrendingUp
    ,MdTurnedIn
    ,MdTurnedInNot
    ,MdUpdate
    ,MdVerifiedUser
    ,MdViewAgenda
    ,MdViewArray
    ,MdViewCarousel
    ,MdViewColumn
    ,MdViewDay
    ,MdViewHeadline
    ,MdViewList
    ,MdViewModule
    ,MdViewQuilt
    ,MdViewStream
    ,MdViewWeek
    ,MdVisibility
    ,MdVisibilityOff
    ,MdWatchLater
    ,MdWork
    ,MdYoutubeSearchedFor
    ,MdZoomIn
    ,MdZoomOut
    ,MdAddAlert
    ,MdError
    ,MdErrorOutline
    ,MdWarning
    ,MdAddToQueue
    ,MdAirplay
    ,MdAlbum
    ,MdArtTrack
    ,MdAvTimer
    ,MdBrandingWatermark
    ,MdCallToAction
    ,MdClosedCaption
    ,MdEqualizer
    ,MdExplicit
    ,MdFastForward
    ,MdFastRewind
    ,MdFeaturedPlayList
    ,MdFeaturedVideo
    ,MdFiberDvr
    ,MdFiberManualRecord
    ,MdFiberNew
    ,MdFiberPin
    ,MdFiberSmartRecord
    ,MdForward10
    ,MdForward30
    ,MdForward5
    ,MdGames
    ,MdHd
    ,MdHearing
    ,MdHighQuality
    ,MdLibraryAdd
    ,MdLibraryBooks
    ,MdLibraryMusic
    ,MdLoop
    ,MdMic
    ,MdMicNone
    ,MdMicOff
    ,MdMovie
    ,MdMusicVideo
    ,MdNewReleases
    ,MdNotInterested
    ,MdNote
    ,MdPause
    ,MdPauseCircleFilled
    ,MdPauseCircleOutline
    ,MdPlayArrow
    ,MdPlayCircleFilled
    ,MdPlayCircleOutline
    ,MdPlaylistAdd
    ,MdPlaylistAddCheck
    ,MdPlaylistPlay
    ,MdQueue
    ,MdQueueMusic
    ,MdQueuePlayNext
    ,MdRadio
    ,MdRecentActors
    ,MdRemoveFromQueue
    ,MdRepeat
    ,MdRepeatOne
    ,MdReplay10
    ,MdReplay
    ,MdReplay30
    ,MdReplay5
    ,MdShuffle
    ,MdSkipNext
    ,MdSkipPrevious
    ,MdSlowMotionVideo
    ,MdSnooze
    ,MdSortByAlpha
    ,MdStop
    ,MdSubscriptions
    ,MdSubtitles
    ,MdSurroundSound
    ,MdVideoCall
    ,MdVideoLabel
    ,MdVideoLibrary
    ,MdVideocam
    ,MdVideocamOff
    ,MdVolumeDown
    ,MdVolumeMute
    ,MdVolumeOff
    ,MdVolumeUp
    ,MdWeb
    ,MdWebAsset
    ,MdBusiness
    ,MdCall
    ,MdCallEnd
    ,MdCallMade
    ,MdCallMerge
    ,MdCallMissed
    ,MdCallMissedOutgoing
    ,MdCallReceived
    ,MdCallSplit
    ,MdChat
    ,MdChatBubble
    ,MdChatBubbleOutline
    ,MdClearAll
    ,MdComment
    ,MdContactMail
    ,MdContactPhone
    ,MdContacts
    ,MdDialerSip
    ,MdDialpad
    ,MdEmail
    ,MdForum
    ,MdImportContacts
    ,MdImportExport
    ,MdInvertColorsOff
    ,MdLiveHelp
    ,MdLocationOff
    ,MdLocationOn
    ,MdMailOutline
    ,MdMessage
    ,MdNoSim
    ,MdPhone
    ,MdPhonelinkErase
    ,MdPhonelinkLock
    ,MdPhonelinkRing
    ,MdPhonelinkSetup
    ,MdPortableWifiOff
    ,MdPresentToAll
    ,MdRingVolume
    ,MdRssFeed
    ,MdScreenShare
    ,MdSpeakerPhone
    ,MdStayCurrentLandscape
    ,MdStayCurrentPortrait
    ,MdStayPrimaryLandscape
    ,MdStayPrimaryPortrait
    ,MdStopScreenShare
    ,MdSwapCalls
    ,MdTextsms
    ,MdVoicemail
    ,MdVpnKey
    ,MdAdd
    ,MdAddBox
    ,MdAddCircle
    ,MdAddCircleOutline
    ,MdArchive
    ,MdBackspace
    ,MdBlock
    ,MdClear
    ,MdContentCopy
    ,MdContentCut
    ,MdContentPaste
    ,MdCreate
    ,MdDeleteSweep
    ,MdDrafts
    ,MdFilterList
    ,MdFlag
    ,MdFontDownload
    ,MdForward
    ,MdGesture
    ,MdInbox
    ,MdLink
    ,MdLowPriority
    ,MdMail
    ,MdMarkunread
    ,MdMoveToInbox
    ,MdNextWeek
    ,MdRedo
    ,MdRemove
    ,MdRemoveCircle
    ,MdRemoveCircleOutline
    ,MdReply
    ,MdReplyAll
    ,MdReport
    ,MdSave
    ,MdSelectAll
    ,MdSend
    ,MdSort
    ,MdTextFormat
    ,MdUnarchive
    ,MdUndo
    ,MdWeekend
    ,MdAccessAlarm
    ,MdAccessAlarms
    ,MdAccessTime
    ,MdAddAlarm
    ,MdAirplanemodeActive
    ,MdAirplanemodeInactive
    ,MdBattery20
    ,MdBattery30
    ,MdBattery50
    ,MdBattery60
    ,MdBattery80
    ,MdBattery90
    ,MdBatteryAlert
    ,MdBatteryCharging20
    ,MdBatteryCharging30
    ,MdBatteryCharging50
    ,MdBatteryCharging60
    ,MdBatteryCharging80
    ,MdBatteryCharging90
    ,MdBatteryChargingFull
    ,MdBatteryFull
    ,MdBatteryStd
    ,MdBatteryUnknown
    ,MdBluetooth
    ,MdBluetoothConnected
    ,MdBluetoothDisabled
    ,MdBluetoothSearching
    ,MdBrightnessAuto
    ,MdBrightnessHigh
    ,MdBrightnessLow
    ,MdBrightnessMedium
    ,MdDataUsage
    ,MdDeveloperMode
    ,MdDevices
    ,MdDvr
    ,MdGpsFixed
    ,MdGpsNotFixed
    ,MdGpsOff
    ,MdGraphicEq
    ,MdLocationDisabled
    ,MdLocationSearching
    ,MdNetworkCell
    ,MdNetworkWifi
    ,MdNfc
    ,MdScreenLockLandscape
    ,MdScreenLockPortrait
    ,MdScreenLockRotation
    ,MdScreenRotation
    ,MdSdStorage
    ,MdSettingsSystemDaydream
    ,MdSignalCellular0Bar
    ,MdSignalCellular1Bar
    ,MdSignalCellular2Bar
    ,MdSignalCellular3Bar
    ,MdSignalCellular4Bar
    ,MdSignalCellularConnectedNoInternet0Bar
    ,MdSignalCellularConnectedNoInternet1Bar
    ,MdSignalCellularConnectedNoInternet2Bar
    ,MdSignalCellularConnectedNoInternet3Bar
    ,MdSignalCellularConnectedNoInternet4Bar
    ,MdSignalCellularNoSim
    ,MdSignalCellularNull
    ,MdSignalCellularOff
    ,MdSignalWifi0Bar
    ,MdSignalWifi1Bar
    ,MdSignalWifi1BarLock
    ,MdSignalWifi2Bar
    ,MdSignalWifi2BarLock
    ,MdSignalWifi3Bar
    ,MdSignalWifi3BarLock
    ,MdSignalWifi4Bar
    ,MdSignalWifi4BarLock
    ,MdSignalWifiOff
    ,MdStorage
    ,MdUsb
    ,MdWallpaper
    ,MdWidgets
    ,MdWifiLock
    ,MdWifiTethering
    ,MdAttachFile
    ,MdAttachMoney
    ,MdBorderAll
    ,MdBorderBottom
    ,MdBorderClear
    ,MdBorderColor
    ,MdBorderHorizontal
    ,MdBorderInner
    ,MdBorderLeft
    ,MdBorderOuter
    ,MdBorderRight
    ,MdBorderStyle
    ,MdBorderTop
    ,MdBorderVertical
    ,MdBubbleChart
    ,MdDragHandle
    ,MdFormatAlignCenter
    ,MdFormatAlignJustify
    ,MdFormatAlignLeft
    ,MdFormatAlignRight
    ,MdFormatBold
    ,MdFormatClear
    ,MdFormatColorFill
    ,MdFormatColorReset
    ,MdFormatColorText
    ,MdFormatIndentDecrease
    ,MdFormatIndentIncrease
    ,MdFormatItalic
    ,MdFormatLineSpacing
    ,MdFormatListBulleted
    ,MdFormatListNumbered
    ,MdFormatPaint
    ,MdFormatQuote
    ,MdFormatShapes
    ,MdFormatSize
    ,MdFormatStrikethrough
    ,MdFormatTextdirectionLToR
    ,MdFormatTextdirectionRToL
    ,MdFormatUnderlined
    ,MdFunctions
    ,MdHighlight
    ,MdInsertChart
    ,MdInsertComment
    ,MdInsertDriveFile
    ,MdInsertEmoticon
    ,MdInsertInvitation
    ,MdInsertLink
    ,MdInsertPhoto
    ,MdLinearScale
    ,MdMergeType
    ,MdModeComment
    ,MdModeEdit
    ,MdMonetizationOn
    ,MdMoneyOff
    ,MdMultilineChart
    ,MdPieChart
    ,MdPieChartOutlined
    ,MdPublish
    ,MdShortText
    ,MdShowChart
    ,MdSpaceBar
    ,MdStrikethroughS
    ,MdTextFields
    ,MdTitle
    ,MdVerticalAlignBottom
    ,MdVerticalAlignCenter
    ,MdVerticalAlignTop
    ,MdWrapText
    ,MdAttachment
    ,MdCloud
    ,MdCloudCircle
    ,MdCloudDone
    ,MdCloudDownload
    ,MdCloudOff
    ,MdCloudQueue
    ,MdCloudUpload
    ,MdCreateNewFolder
    ,MdFileDownload
    ,MdFileUpload
    ,MdFolder
    ,MdFolderOpen
    ,MdFolderShared
    ,MdCast
    ,MdCastConnected
    ,MdComputer
    ,MdDesktopMac
    ,MdDesktopWindows
    ,MdDeveloperBoard
    ,MdDeviceHub
    ,MdDevicesOther
    ,MdDock
    ,MdGamepad
    ,MdHeadset
    ,MdHeadsetMic
    ,MdKeyboard
    ,MdKeyboardArrowDown
    ,MdKeyboardArrowLeft
    ,MdKeyboardArrowRight
    ,MdKeyboardArrowUp
    ,MdKeyboardBackspace
    ,MdKeyboardCapslock
    ,MdKeyboardHide
    ,MdKeyboardReturn
    ,MdKeyboardTab
    ,MdKeyboardVoice
    ,MdLaptop
    ,MdLaptopChromebook
    ,MdLaptopMac
    ,MdLaptopWindows
    ,MdMemory
    ,MdMouse
    ,MdPhoneAndroid
    ,MdPhoneIphone
    ,MdPhonelink
    ,MdPhonelinkOff
    ,MdPowerInput
    ,MdRouter
    ,MdScanner
    ,MdSecurity
    ,MdSimCard
    ,MdSmartphone
    ,MdSpeaker
    ,MdSpeakerGroup
    ,MdTablet
    ,MdTabletAndroid
    ,MdTabletMac
    ,MdToys
    ,MdTv
    ,MdVideogameAsset
    ,MdWatch
    ,MdAddAPhoto
    ,MdAddToPhotos
    ,MdAdjust
    ,MdAssistant
    ,MdAssistantPhoto
    ,MdAudiotrack
    ,MdBlurCircular
    ,MdBlurLinear
    ,MdBlurOff
    ,MdBlurOn
    ,MdBrightness1
    ,MdBrightness2
    ,MdBrightness3
    ,MdBrightness4
    ,MdBrightness5
    ,MdBrightness6
    ,MdBrightness7
    ,MdBrokenImage
    ,MdBrush
    ,MdBurstMode
    ,MdCamera
    ,MdCameraAlt
    ,MdCameraFront
    ,MdCameraRear
    ,MdCameraRoll
    ,MdCenterFocusStrong
    ,MdCenterFocusWeak
    ,MdCollections
    ,MdCollectionsBookmark
    ,MdColorLens
    ,MdColorize
    ,MdCompare
    ,MdControlPoint
    ,MdControlPointDuplicate
    ,MdCrop169
    ,MdCrop
    ,MdCrop32
    ,MdCrop54
    ,MdCrop75
    ,MdCropDin
    ,MdCropFree
    ,MdCropLandscape
    ,MdCropOriginal
    ,MdCropPortrait
    ,MdCropRotate
    ,MdCropSquare
    ,MdDehaze
    ,MdDetails
    ,MdEdit
    ,MdExposure
    ,MdExposureNeg1
    ,MdExposureNeg2
    ,MdExposurePlus1
    ,MdExposurePlus2
    ,MdExposureZero
    ,MdFilter1
    ,MdFilter2
    ,MdFilter
    ,MdFilter3
    ,MdFilter4
    ,MdFilter5
    ,MdFilter6
    ,MdFilter7
    ,MdFilter8
    ,MdFilter9
    ,MdFilter9Plus
    ,MdFilterBAndW
    ,MdFilterCenterFocus
    ,MdFilterDrama
    ,MdFilterFrames
    ,MdFilterHdr
    ,MdFilterNone
    ,MdFilterTiltShift
    ,MdFilterVintage
    ,MdFlare
    ,MdFlashAuto
    ,MdFlashOff
    ,MdFlashOn
    ,MdFlip
    ,MdGradient
    ,MdGrain
    ,MdGridOff
    ,MdGridOn
    ,MdHdrOff
    ,MdHdrOn
    ,MdHdrStrong
    ,MdHdrWeak
    ,MdHealing
    ,MdImage
    ,MdImageAspectRatio
    ,MdIso
    ,MdLandscape
    ,MdLeakAdd
    ,MdLeakRemove
    ,MdLens
    ,MdLinkedCamera
    ,MdLooks
    ,MdLooks3
    ,MdLooks4
    ,MdLooks5
    ,MdLooks6
    ,MdLooksOne
    ,MdLooksTwo
    ,MdLoupe
    ,MdMonochromePhotos
    ,MdMovieCreation
    ,MdMovieFilter
    ,MdMusicNote
    ,MdNature
    ,MdNaturePeople
    ,MdNavigateBefore
    ,MdNavigateNext
    ,MdPalette
    ,MdPanorama
    ,MdPanoramaFishEye
    ,MdPanoramaHorizontal
    ,MdPanoramaVertical
    ,MdPanoramaWideAngle
    ,MdPhoto
    ,MdPhotoAlbum
    ,MdPhotoCamera
    ,MdPhotoFilter
    ,MdPhotoLibrary
    ,MdPhotoSizeSelectActual
    ,MdPhotoSizeSelectLarge
    ,MdPhotoSizeSelectSmall
    ,MdPictureAsPdf
    ,MdPortrait
    ,MdRemoveRedEye
    ,MdRotate90DegreesCcw
    ,MdRotateLeft
    ,MdRotateRight
    ,MdSlideshow
    ,MdStraighten
    ,MdStyle
    ,MdSwitchCamera
    ,MdSwitchVideo
    ,MdTagFaces
    ,MdTexture
    ,MdTimelapse
    ,MdTimer10
    ,MdTimer
    ,MdTimer3
    ,MdTimerOff
    ,MdTonality
    ,MdTransform
    ,MdTune
    ,MdViewComfy
    ,MdViewCompact
    ,MdVignette
    ,MdWbAuto
    ,MdWbCloudy
    ,MdWbIncandescent
    ,MdWbIridescent
    ,MdWbSunny
    ,MdAddLocation
    ,MdBeenhere
    ,MdDirections
    ,MdDirectionsBike
    ,MdDirectionsBoat
    ,MdDirectionsBus
    ,MdDirectionsCar
    ,MdDirectionsRailway
    ,MdDirectionsRun
    ,MdDirectionsSubway
    ,MdDirectionsTransit
    ,MdDirectionsWalk
    ,MdEditLocation
    ,MdEvStation
    ,MdFlight
    ,MdHotel
    ,MdLayers
    ,MdLayersClear
    ,MdLocalActivity
    ,MdLocalAirport
    ,MdLocalAtm
    ,MdLocalBar
    ,MdLocalCafe
    ,MdLocalCarWash
    ,MdLocalConvenienceStore
    ,MdLocalDining
    ,MdLocalDrink
    ,MdLocalFlorist
    ,MdLocalGasStation
    ,MdLocalGroceryStore
    ,MdLocalHospital
    ,MdLocalHotel
    ,MdLocalLaundryService
    ,MdLocalLibrary
    ,MdLocalMall
    ,MdLocalMovies
    ,MdLocalOffer
    ,MdLocalParking
    ,MdLocalPharmacy
    ,MdLocalPhone
    ,MdLocalPizza
    ,MdLocalPlay
    ,MdLocalPostOffice
    ,MdLocalPrintshop
    ,MdLocalSee
    ,MdLocalShipping
    ,MdLocalTaxi
    ,MdMap
    ,MdMyLocation
    ,MdNavigation
    ,MdNearMe
    ,MdPersonPin
    ,MdPersonPinCircle
    ,MdPinDrop
    ,MdPlace
    ,MdRateReview
    ,MdRestaurant
    ,MdRestaurantMenu
    ,MdSatellite
    ,MdStoreMallDirectory
    ,MdStreetview
    ,MdSubway
    ,MdTerrain
    ,MdTraffic
    ,MdTrain
    ,MdTram
    ,MdTransferWithinAStation
    ,MdZoomOutMap
    ,MdApps
    ,MdArrowBack
    ,MdArrowDownward
    ,MdArrowDropDown
    ,MdArrowDropDownCircle
    ,MdArrowDropUp
    ,MdArrowForward
    ,MdArrowUpward
    ,MdCancel
    ,MdCheck
    ,MdChevronLeft
    ,MdChevronRight
    ,MdClose
    ,MdExpandLess
    ,MdExpandMore
    ,MdFirstPage
    ,MdFullscreen
    ,MdFullscreenExit
    ,MdLastPage
    ,MdMenu
    ,MdMoreHoriz
    ,MdMoreVert
    ,MdRefresh
    ,MdSubdirectoryArrowLeft
    ,MdSubdirectoryArrowRight
    ,MdUnfoldLess
    ,MdUnfoldMore
    ,MdAdb
    ,MdAirlineSeatFlat
    ,MdAirlineSeatFlatAngled
    ,MdAirlineSeatIndividualSuite
    ,MdAirlineSeatLegroomExtra
    ,MdAirlineSeatLegroomNormal
    ,MdAirlineSeatLegroomReduced
    ,MdAirlineSeatReclineExtra
    ,MdAirlineSeatReclineNormal
    ,MdBluetoothAudio
    ,MdConfirmationNumber
    ,MdDiscFull
    ,MdDoNotDisturb
    ,MdDoNotDisturbAlt
    ,MdDoNotDisturbOff
    ,MdDoNotDisturbOn
    ,MdDriveEta
    ,MdEnhancedEncryption
    ,MdEventAvailable
    ,MdEventBusy
    ,MdEventNote
    ,MdFolderSpecial
    ,MdLiveTv
    ,MdMms
    ,MdMore
    ,MdNetworkCheck
    ,MdNetworkLocked
    ,MdNoEncryption
    ,MdOndemandVideo
    ,MdPersonalVideo
    ,MdPhoneBluetoothSpeaker
    ,MdPhoneForwarded
    ,MdPhoneInTalk
    ,MdPhoneLocked
    ,MdPhoneMissed
    ,MdPhonePaused
    ,MdPower
    ,MdPriorityHigh
    ,MdRvHookup
    ,MdSdCard
    ,MdSimCardAlert
    ,MdSms
    ,MdSmsFailed
    ,MdSync
    ,MdSyncDisabled
    ,MdSyncProblem
    ,MdSystemUpdate
    ,MdTapAndPlay
    ,MdTimeToLeave
    ,MdVibration
    ,MdVoiceChat
    ,MdVpnLock
    ,MdWc
    ,MdWifi
    ,MdAcUnit
    ,MdAirportShuttle
    ,MdAllInclusive
    ,MdBeachAccess
    ,MdBusinessCenter
    ,MdCasino
    ,MdChildCare
    ,MdChildFriendly
    ,MdFitnessCenter
    ,MdFreeBreakfast
    ,MdGolfCourse
    ,MdHotTub
    ,MdKitchen
    ,MdPool
    ,MdRoomService
    ,MdSmokeFree
    ,MdSmokingRooms
    ,MdSpa
    ,MdCake
    ,MdDomain
    ,MdGroup
    ,MdGroupAdd
    ,MdLocationCity
    ,MdMood
    ,MdMoodBad
    ,MdNotifications
    ,MdNotificationsActive
    ,MdNotificationsNone
    ,MdNotificationsOff
    ,MdNotificationsPaused
    ,MdPages
    ,MdPartyMode
    ,MdPeople
    ,MdPeopleOutline
    ,MdPerson
    ,MdPersonAdd
    ,MdPersonOutline
    ,MdPlusOne
    ,MdPoll
    ,MdPublic
    ,MdSchool
    ,MdSentimentDissatisfied
    ,MdSentimentNeutral
    ,MdSentimentSatisfied
    ,MdSentimentVeryDissatisfied
    ,MdSentimentVerySatisfied
    ,MdShare
    ,MdWhatshot
    ,MdCheckBox
    ,MdCheckBoxOutlineBlank
    ,MdIndeterminateCheckBox
    ,MdRadioButtonChecked
    ,MdRadioButtonUnchecked
    ,MdStar
    ,MdStarBorder
    ,MdStarHalf } from "react-icons/md";
    import Link from 'next/link'
    
    import {
      Collapse,Container, Row, Col,
      Button,
      Navbar,
      NavbarToggler,
      NavbarBrand,
      Nav,
      NavItem,
      NavLink,
      UncontrolledDropdown,
      DropdownToggle,
      DropdownMenu,
      DropdownItem,
      Breadcrumb,BreadcrumbItem,
      NavbarText
    } from 'reactstrap';
function MyApp({ Component, pageProps }) {
    return <Component {...pageProps} />
  }
  
  // Only uncomment this method if you have blocking data requirements for
  // every single page in your application. This disables the ability to
  // perform automatic static optimization, causing every page in your app to
  // be server-side rendered.
  //
  // MyApp.getInitialProps = async (appContext) => {
  //   // calls page's `getInitialProps` and fills `appProps.pageProps`
  //   const appProps = await App.getInitialProps(appContext);
  //
  //   return { ...appProps }
  // }
  
  export default MyApp